version: '3.8'
services:
  postgres:
    image: docker.io/postgres:17
    restart: always
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ric
volumes:
  db:
    diver: local